# Generated by Django 3.0.5 on 2020-05-08 16:59

import builtins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crystal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crystal_name', models.CharField(max_length=100)),
                ('regeneration', models.IntegerField()),
                ('stamina', models.IntegerField()),
                ('mastery', models.IntegerField()),
                ('damage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('stamina', models.IntegerField()),
                ('mastery', models.IntegerField()),
                ('gold', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monster_name', models.CharField(max_length=100)),
                ('stamina', models.IntegerField()),
                ('mastery', models.IntegerField()),
                ('damage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RPG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(unique=True)),
                ('story', models.TextField()),
                ('answer_choice_1', models.TextField(blank=True, null=True)),
                ('answer_link_1', models.IntegerField(blank=True, null=True)),
                ('answer_choice_2', models.TextField(blank=True, null=True)),
                ('answer_link_2', models.IntegerField(blank=True, null=True)),
                ('answer_choice_3', models.TextField(blank=True, null=True)),
                ('answer_link_3', models.IntegerField(blank=True, null=True)),
                ('answer_choice_4', models.TextField(blank=True, null=True)),
                ('answer_link_4', models.IntegerField(blank=True, null=True)),
                ('answer_choice_5', models.TextField(blank=True, null=True)),
                ('answer_link_5', models.IntegerField(blank=True, null=True)),
                ('monster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='RPG.Monster')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_mastery', models.IntegerField(default=12)),
                ('current_mastery', models.IntegerField(default=12)),
                ('default_stamina', models.IntegerField(default=22)),
                ('current_stamina', models.IntegerField(default=22)),
                ('default_luck', models.IntegerField(default=11)),
                ('current_luck', models.IntegerField(default=11)),
                ('armor', models.IntegerField(default=builtins.id)),
                ('helmet', models.IntegerField(default=builtins.id)),
                ('weapon', models.IntegerField(default=builtins.id)),
                ('gold', models.IntegerField(default=3)),
                ('stamina_crystal', models.IntegerField(default=0)),
                ('earth_crystal', models.IntegerField(default=0)),
                ('water_crystal', models.IntegerField(default=0)),
                ('fire_crystal', models.IntegerField(default=0)),
                ('wind_crystal', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonsterStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamina', models.IntegerField()),
                ('mastery', models.IntegerField()),
                ('damage', models.IntegerField()),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='RPG.Monster')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
