# Generated by Django 3.0.5 on 2020-04-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RPG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(unique=True)),
                ('story', models.TextField()),
                ('answer_choice_1', models.TextField()),
                ('answer_link_1', models.IntegerField()),
                ('answer_choice_2', models.TextField()),
                ('answer_link_2', models.IntegerField()),
                ('answer_choice_3', models.TextField()),
                ('answer_link_3', models.IntegerField()),
                ('answer_choice_4', models.TextField()),
                ('answer_link_4', models.IntegerField()),
                ('answer_choice_5', models.TextField()),
                ('answer_link_5', models.IntegerField()),
            ],
        ),
    ]
