# Generated by Django 3.0.5 on 2020-05-08 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RPG', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='page_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='armor',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_luck',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_mastery',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_stamina',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='profile',
            name='default_luck',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='profile',
            name='default_mastery',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='profile',
            name='default_stamina',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gold',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='helmet',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weapon',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='rpg',
            name='monster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='RPG.Monster'),
        ),
    ]
