# Generated by Django 3.0.5 on 2020-05-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPG', '0002_auto_20200508_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='page_number',
            new_name='last_number',
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_mastery',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_stamina',
            field=models.IntegerField(default=21),
        ),
        migrations.AlterField(
            model_name='profile',
            name='default_mastery',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='default_stamina',
            field=models.IntegerField(default=21),
        ),
    ]
