# Generated by Django 3.0.5 on 2020-05-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPG', '0003_auto_20200509_0211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='last_number',
            new_name='last_page',
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_luck',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_mastery',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_stamina',
            field=models.IntegerField(default=22),
        ),
        migrations.AlterField(
            model_name='profile',
            name='default_luck',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='profile',
            name='default_mastery',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='profile',
            name='default_stamina',
            field=models.IntegerField(default=22),
        ),
    ]
