# Generated by Django 3.0.5 on 2020-05-13 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RPG', '0004_auto_20200509_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crystal',
            name='damage',
        ),
        migrations.RemoveField(
            model_name='crystal',
            name='mastery',
        ),
        migrations.RemoveField(
            model_name='crystal',
            name='regeneration',
        ),
        migrations.RemoveField(
            model_name='crystal',
            name='stamina',
        ),
        migrations.AddField(
            model_name='rpg',
            name='crystal_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='RPG.Crystal'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_luck',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_mastery',
            field=models.IntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_stamina',
            field=models.IntegerField(default=19),
        ),
        migrations.AlterField(
            model_name='profile',
            name='default_luck',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='profile',
            name='default_mastery',
            field=models.IntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='profile',
            name='default_stamina',
            field=models.IntegerField(default=19),
        ),
    ]
