# Generated by Django 3.0.5 on 2020-06-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPG', '0005_auto_20200513_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_mastery',
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_stamina',
            field=models.IntegerField(default=22),
        ),
        migrations.AlterField(
            model_name='profile',
            name='default_mastery',
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='profile',
            name='default_stamina',
            field=models.IntegerField(default=22),
        ),
    ]
